# Generated by Django 6.1.1 on 2026-09-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('date', models.DateField(verbose_name='Data da Reserva')),
                ('hour', models.TimeField(verbose_name='Hora')),
                ('number_people', models.PositiveIntegerField(verbose_name='Nº de Pessoas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações (Opcional)')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
