# Generated by Django 6.1.1 on 2026-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('imagem', models.ImageField(upload_to='eventos/', verbose_name='Cartaz/Foto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)')),
            ],
        ),
    ]
