# Generated by Django 6.1.1 on 2026-09-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Events',
        ),
    ]
