# Generated by Django 6.1.1 on 2026-09-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_evento_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
